apiVersion: v1
kind: Secret
metadata:
  name: admin-password
  namespace: learn-sdn-hub
type: Opaque
stringData:
  password: "test123"
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: prona4-db
  namespace: learn-sdn-hub
spec:
  members: 3
  type: ReplicaSet
  version: "8.2.0"
  security:
    authentication:
      modes: ["SCRAM-SHA-256"]
      #modes: []
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: admin-password
      roles:
        - name: root 
          db: admin
      scramCredentialsSecretName: admin-scram-credentials
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "local-path"
            resources:
              requests:
                storage: 5Gi