apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "learn-sdn-hub.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
    {{- include "learn-sdn-hub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      {{- include "learn-sdn-hub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
        {{- include "learn-sdn-hub.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP
          {{- if .Values.frontend.env }}
          env:
            {{- toYaml .Values.frontend.env | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
