#!/bin/bash
SESSION="Ex3-bash"
WORKDIR="/home/p4/p4-boilerplate/Example3-LearningSwitch"
COMMAND="sudo p4run"

tmux start-server
tmux has-session -t $SESSION 2>/dev/null
if [ $? != 0 ]; then
  tmux new-session -d -n $SESSION -s $SESSION
  tmux send-keys -t $SESSION "cd $WORKDIR" Enter "$COMMAND" Enter
fi
tmux attach-session -t $SESSION
