{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
    cert-manager.io/private-key-size: "4096"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: {{ .Values.frontend.service.servicePort }}
            pathType: Prefix
            path: /
          - backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  number: {{ .Values.frontend.service.servicePort }}
            pathType: Prefix
            path: /api
      host: {{ .Values.ingress.fqdn }}
  tls:
    - hosts:
      - {{ .Values.ingress.fqdn | quote }}
      secretName: {{ .Values.ingress.fqdn }}
{{- end }}
