apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.servicePort | int }}
      targetPort: {{ .Values.backend.service.containerPort | int }}
