apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.servicePort | int}}
      targetPort: {{ .Values.frontend.service.containerPort | int }}
