name: Node.js CI
on: [push]
jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["22"]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: cd backend && npm install
      - run: cd backend && npm test
      - run: cd backend && npm run lint
      - run: cd backend && npm run type-check
        env:
          CI: true

  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["22"]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: cd frontend && npm install
      - run: cd frontend && npm run build
        env:
          CI: true
